### ISSUE TITLE
Estou começando a aprender programação, vi seu código e pensei em outra forma de resolver

### ISSUE THREAD

**Issue by MatheusSousa5068** [LuanPetruitis/minis_programas_python#1]
```
e = int(input('escolha um numero inteiro para fazer a tabuada:  '))
for c in range(11):
   t = e * c
   print(f'{e} * {c} = {t}')
```

**Comment by LuanPetruitis** [comment]
# Mudança do código
---
Olhei a sua solução @MatheusSousa5068  e comparei com a minha e creio que o seu código ficou mais, adequado com menos linhas, já fiz as mudanças.

Estou começando, mas quero cada vez fazer coisas maiores.
**OBRIGADO PELA ATENÇÃO, VAMOS JUNTOS APRENDENDO CADA VEZ MAIS**
